-- ============================================================
--  schema_rds.sql
--  Database schema for AWS RDS PostgreSQL 15
--  Spot Warsaw Guide
--
--  NOTE: This file is NOT generated by pg_dump from the local
--  TimescaleDB database — pg_dump output contains extensions
--  and constructs incompatible with RDS, including:
--    - CREATE EXTENSION timescaledb
--    - Hypertable definitions
--    - vectorscale / DiskANN index extensions
--  This schema was written manually, omitting all TimescaleDB
--  specific constructs.
--
--  Key differences from local (Docker) setup:
--    - embeddings: hypertable + DiskANN  →  regular table + HNSW
--    - Vector search operator <=> remains identical
--    - Backend requires no code changes
--    - chat_sessions, chat_messages, saved_places created empty
--      (user data starts fresh on the new RDS instance)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;   
CREATE EXTENSION IF NOT EXISTS pg_trgm;   


CREATE TABLE IF NOT EXISTS public.places (
    id                      TEXT                NOT NULL,
    name                    TEXT,
    address                 TEXT,
    address_context         TEXT,
    lat                     DOUBLE PRECISION,
    lon                     DOUBLE PRECISION,
    district                TEXT,
    primary_type            TEXT,
    maps_url                TEXT,
    main_category           TEXT,
    sub_category            TEXT,
    rating                  DOUBLE PRECISION,
    user_rating_count       DOUBLE PRECISION,
    price_level             TEXT,
    price_range_start       DOUBLE PRECISION,
    price_range_end         DOUBLE PRECISION,
    website                 TEXT,
    opening_hours           TEXT,
    takeout                 BOOLEAN,
    dine_in                 BOOLEAN,
    reservable              BOOLEAN,
    outdoor_seating         BOOLEAN,
    serves_breakfast        BOOLEAN,
    serves_lunch            BOOLEAN,
    serves_dinner           BOOLEAN,
    serves_beer             BOOLEAN,
    serves_wine             BOOLEAN,
    serves_cocktails        BOOLEAN,
    serves_coffee           BOOLEAN,
    serves_vegetarian       BOOLEAN,
    good_for_groups         BOOLEAN,
    live_music              BOOLEAN,
    menu_for_children       BOOLEAN,
    serves_dessert          BOOLEAN,
    google_maps_direct_link TEXT,
    menu_url                TEXT,
    editorial_summary       TEXT,

    CONSTRAINT places_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.embeddings (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    metadata    JSONB,
    contents    TEXT,
    embedding   VECTOR(1536),

    CONSTRAINT embeddings_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id     TEXT,
    created_at  TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.chat_messages (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
    session_id          UUID        REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    role                TEXT,
    content             TEXT,
    message_type        TEXT,
    recommended_places  JSONB[],
    created_at          TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.saved_places (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id         TEXT,
    place_id        TEXT        REFERENCES public.places(id) ON DELETE CASCADE,
    session_id      TEXT,
    is_favourite    BOOLEAN     DEFAULT true,
    created_at      TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT saved_places_pkey PRIMARY KEY (id),
    CONSTRAINT saved_places_user_place_unique UNIQUE (user_id, place_id)
);


CREATE INDEX IF NOT EXISTS idx_chat_messages_content_trgm
    ON public.chat_messages
    USING gin (content gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id
    ON public.chat_messages (session_id);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id
    ON public.chat_sessions (user_id);

